FROM python:3.11

RUN apt update \
	&& apt install -y --no-install-recommends --no-install-suggests \
	build-essential \
	&& pip install --no-cache-dir --upgrade pip

WORKDIR /app
COPY ./requirements.txt /app
RUN pip install --no-cache-dir --requirement /app/requirements.txt
COPY . /app

EXPOSE 8080
CMD ["python","server.py"]