apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wss-server-rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard